Create Task3.txt
opencodeiiita/CyberRepo-2077 pull request #336
Opened 2023-12-27 17:39 UTC by CodinJack

Issue: #306

2023-12-28 06:49 UTC, DRedDevil04 requested changes
what exactly will happen when you exploit it...what unintended consequence will happen wrt this particular program

2023-12-28 07:14 UTC, CodinJack commented
@DRedDevil04 made changes, please review

2023-12-28 20:57 UTC, DRedDevil04 commented
you are thinking at a very high level....think of it in terms of the low level consequences....it is not very hard to spot

2023-12-30 07:37 UTC, DRedDevil04 commented
@CodinJack you have until 3 pm to make the changes, after which ill be closing the issue

2023-12-30 07:53 UTC, CodinJack commented
is it not about one gaining unauthorized access by overwriting the return address on the stack and making the program jump to the "Access Granted" message?🥲

2023-12-30 08:22 UTC, DRedDevil04 commented
There is a much simpler exploit….just give me the string which will print access granted(except the 2 passwords)

2023-12-30 08:32 UTC, CodinJack commented
made changes to the doc file, please review

2024-01-01 06:14 UTC, merged